# Generated by Django 4.2.1 on 2023-05-19 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimages',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='config.hotel'),
        ),
    ]
