# Generated by Django 4.2.1 on 2023-05-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_hotelimages_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelimages',
            old_name='images',
            new_name='image',
        ),
    ]
